services:
  server:
    build:
      context: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - ORIGIN=https://www.whosfritz.de
    depends_on:
      - mongo_container
    restart: always


  mongo_container:
    image: mongo:latest
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_container:/data/db
    restart: always

volumes:
  mongo_container: