version: '3.8'

services:
  server:
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - ORIGIN=https://www.whosfritz.de
    depends_on:
      - mongo_container
    restart: unless-stopped
    networks:
      - portfolio_network

  mongo_container:
    image: mongo:latest
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_container:/data/db
    restart: unless-stopped
    networks:
      - portfolio_network

volumes:
  mongo_container:

networks:
  portfolio_network:
    external: true
