services:
  server:
    build: .
    ports:
      - $SERVER_PORT:3000
    depends_on:
      - mongo_container
    restart: unless-stopped
    networks:
      - portfolio_network

  mongo_container:
    image: mongo:latest
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_container:/data/db
    restart: unless-stopped
    networks:
      - portfolio_network

volumes:
  mongo_container:


networks:
  portfolio_network:
    external: true
